### PR TITLE
Add Vue 3 compatibility

### PR DESCRIPTION
**Pull request by dmitrystas**

### CODE REVIEW

**Comment by therenney** [comment]
Any chance this gets reviewed and merged soon @Denyllon ?

**Comment by Denyllon** [comment]
@wchmiel Just told me that there are some problems with this PR, but I will take a look on it in upcoming week! Thanks for reminder.

**Comment by GTB3NW** [comment]
It would be great to see vue 3 support added. Any word on when you'll review this @Denyllon ?

**Comment by ssuess** [comment]
Any word on when Vue3 support will be added? I really need to upgrade my project and don't want to have to rewrite all of my charts to use https://github.com/smithalan92/vue3-highcharts Thanks!

**Comment by Denyllon** [comment]
@ssuess @arivero @GTB3NW Sorry for not responding such a long time, but actually we're working on getting this wrapper to support both Vue versions, and we need to precisely walk through a whole process of testing this library on a different configurations. I will let you guys know about the result soon, but I hopefully think that should be finished until the end of upcoming week.

Kind regards!

**Comment by Denyllon** [comment]
Hello @dmitrystas @ssuess @GTB3NW @arivero, and the other who are waiting this package to support Vue v3.
Closing this PR, as it only allowed us to use the `highcharts-vue` wrapper with Vue v3, and due to lack of backward compatibility we decided to do it on our end.

The good news is that the `v1.4.0` is out now, and currently you can use the package with all Vue library versions though 🎉 

Kind regards and thank you for your patience while waiting for this update!

**Pull request closed without merging**
